# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "xhci_pci" "thunderbolt" "vmd" "nvme" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems = {
    "/" = {
      device = "none";
      fsType = "tmpFs";
      options = [ "defaults" "mode=755" ];
    };

    "/boot" = {
      # PLS FIX
      device = "/dev/disk/by-label/SMTH";
      fsType = "vfat";
      options = [ "defaults" "umask=0077" ];
    };

    "/nix" = {
      # PLS FIX
      device = "/dev/disk/by-label/smth";
      fstype = "ext4";
      options = [ "noatime" ];
    };

    "/persist" = {
      # PLS FIX
      device = "/dev/disk/by-label/smth";
      fstype = "ext4";
      options = [ "noatime" ];
      neededForBoot = true;
    };
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
